import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// ---- GOOGLE FONTS ----
const geistSansGoogle = Geist({
  variable: "--font-geist-sans-google",
  subsets: ["latin"],
});

const geistMonoGoogle = Geist_Mono({
  variable: "--font-geist-mono-google",
  subsets: ["latin"],
});

// ---- LOCAL FALLBACK FONTS ----
const geistSansLocal = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans-local",
});

const geistMonoLocal = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono-local",
});

// ---- METADATA ----
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ---- LAYOUT ----
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSansGoogle.variable} 
          ${geistSansLocal.variable} 
          ${geistMonoGoogle.variable} 
          ${geistMonoLocal.variable}
          antialiased
        `}
        style={{
          // Google -> Local fallback
          fontFamily: `var(--font-geist-sans-google), var(--font-geist-sans-local), sans-serif`,
        }}
      >
        {children}
      </body>
    </html>
  );
}
